"""Regenerate files derived from src/videopip/guide.md and the spec models.

    python scripts/sync_docs.py          # write
    python scripts/sync_docs.py --check  # CI: fail if anything is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from videopip import config  # noqa: E402

GUIDE = (ROOT / "src/videopip/guide.md").read_text(encoding="utf-8")

SKILL_HEAD = """---
name: videopip
description: Plan and render videos with VideoPip - product reviews, top-N countdowns, YouTube videos, Shorts, Reels and TikToks from source clips. Use when the user asks to make, edit, cut, script or render a video from clips, or mentions videopip / project.yaml.
---

<!-- generated from src/videopip/guide.md by scripts/sync_docs.py - edit the guide, not this file -->

**Tools:** use the `videopip` MCP tools when they are available (`get_guide`, `analyze_clips`,
`write_project`, `preflight`, `render_start`...). Otherwise use the `videopip` CLI through the
shell. If neither works, tell the user to run `pip install "videopip[mcp]"` and `videopip setup`.

"""

PROMPT_HEAD = """# VideoPip prompt (paste into ChatGPT, Gemini, or any AI chat)

<!-- generated from src/videopip/guide.md by scripts/sync_docs.py -->

You are helping me make a video with **VideoPip**, a command-line video pipeline. You can't run
commands, so: ask me for anything you need (clip names and durations, and the output of
`videopip analyze <clips folder>`), write the complete `project.yaml` in one code block, and tell
me which commands to run. When I paste preflight errors back, fix the YAML.

My request is at the end of this message.

---

"""

PROMPT_TAIL = """
---

## My request

(write what you want here: products/topics, order, length, tone, format, links, and paste the output of
`videopip analyze ./clips`)
"""


def tname(ann) -> str:
    import types
    from typing import Literal, Union, get_args, get_origin
    o = get_origin(ann)
    if o is Literal:
        return " / ".join(str(a) for a in get_args(ann))
    if o in (Union, types.UnionType):
        return " or ".join(tname(a) for a in get_args(ann) if a is not type(None))
    if o in (list, tuple, dict):
        return f"{o.__name__}[{', '.join(tname(a) for a in get_args(ann))}]"
    return getattr(ann, "__name__", str(ann))


def field_table(model, prefix="") -> list[str]:
    rows = []
    for name, f in model.model_fields.items():
        ann = f.annotation
        sub = None
        for cand in getattr(ann, "__args__", ()) + (ann,):
            if isinstance(cand, type) and issubclass(cand, config._M):
                sub = cand
        default = f.default if f.default_factory is None else "..."
        if default is not None and not isinstance(default, (str, int, float, bool)):
            default = "..."
        typ = tname(ann)
        desc = (f.description or "").replace("|", "\\|")
        rows.append(f"| `{prefix}{name}` | {typ.replace('|', '/')} | `{default}` | {desc} |")
        if sub is not None and sub is not model:
            rows += field_table(sub, f"{prefix}{name}.")
    return rows


def spec_md() -> str:
    lines = ["# project.yaml reference", "",
             "<!-- generated by scripts/sync_docs.py from src/videopip/config.py -->", "",
             "Machine-readable schema: `videopip schema`. Guide for AI tools: `videopip guide`.", ""]
    sections = [("Project (top level)", config.Project, ""), ("clips.<id>", config.ClipSpec, ""),
                ("segments[]", config.Segment, ""), ("segments[].forced[]", config.ForcedTake, ""),
                ("segments[].sfx[]", config.SegmentSfx, ""), ("segments[].overlays[]", config.OverlaySpec, ""),
                ("segments[].callouts[]", config.Callout, ""), ("intro.shots[]", config.IntroShot, ""),
                ("shorts[]", config.ShortSpec, ""), ("thumbnail.images[]", config.ThumbImage, "")]
    for title, model, pre in sections:
        lines += [f"## {title}", "", "| field | type | default | description |", "|---|---|---|---|"]
        rows = field_table(model, pre)
        if model is config.Project:
            rows = [r for r in rows if not r.startswith(("| `clips.", "| `segments.", "| `shorts.",
                                                          "| `thumbnail.images"))]
        lines += rows + [""]
    return "\n".join(lines)


def targets() -> dict[Path, str]:
    return {
        ROOT / "plugin/skills/videopip/SKILL.md": SKILL_HEAD + GUIDE,
        ROOT / "PROMPT.md": PROMPT_HEAD + GUIDE + PROMPT_TAIL,
        ROOT / "docs/SPEC.md": spec_md(),
    }


def main():
    check = "--check" in sys.argv
    stale = []
    for path, text in targets().items():
        cur = path.read_text(encoding="utf-8") if path.exists() else None
        if cur != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if check and stale:
        print("stale generated files:", *[str(p.relative_to(ROOT)) for p in stale], sep="\n  ")
        sys.exit(1)
    print("up to date" if not stale else f"wrote {len(stale)} file(s)")


if __name__ == "__main__":
    main()
